### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by baolongt** [dfinity/portal#2976]
![image](https://github.com/dfinity/portal/assets/57053685/4479c656-f274-4cdd-b20f-ed5d93db42eb)

The command should be 
```
dfx cycles top-up `CANISTER_ID`  `AMOUNT`--network ic


dfx wallet send `CANISTER_ID` `AMOUNT`--network ic
```

**Comment by jessiemongeon1** [comment]
Hi, this documentation is correct. It uses the new cycles ledger rather than the cycles wallet. I've added a note in that page to indicate this.

Here is the reference for the cycles top-up command:
https://internetcomputer.org/docs/current/developer-docs/developer-tools/cli-tools/cli-reference/dfx-cycles/#dfx-cycles-top-up
