### ISSUE TITLE
dfx documentation not up to date

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#815]
dfx `0.12.0` features thing like `dfx nns install` that are not documented at all. i propose that with every major/minor release of dfx, an updated version of the docs has to be provided that is feature complete. users should be able to look at old documentations, similar to the python docs where you can pick the version of the docs you want to look at

**Comment by sesi200** [comment]
We’re not quite sure what we want to do with `dfx nns install/import` since it’s a maintainability nightmare the way it is right now. But yes, it would make sense to add a documentation once it’s a bit more clear what will happen to those commands

In general, the docs are updated with a simple `git submodule update`

**Comment by jessiemongeon1** [comment]
Documentation for `dfx nns` now exists: https://internetcomputer.org/docs/current/developer-docs/developer-tools/cli-tools/cli-reference/dfx-nns
